// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package sqlc

import (
	"database/sql"
	"time"
)

type Event struct {
	ID          int32
	Name        string
	Description sql.NullString
	StartDate   time.Time
	EndDate     sql.NullTime
	OneTime     bool
}
