// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	GetEvent(ctx context.Context, id int32) (Event, error)
	GetEvents(ctx context.Context, arg GetEventsParams) ([]Event, error)
}

var _ Querier = (*Queries)(nil)
